# Generated by Django 2.0.8 on 2018-09-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, help_text='в рублях', max_digits=12, verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ИНН'),
        ),
    ]
