# Generated by Django 2.0.8 on 2018-09-26 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180926_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, help_text='в рублях', max_digits=12, verbose_name='Сумма')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Кредитор')),
            ],
        ),
        migrations.CreateModel(
            name='Transatcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, help_text='в рублях', max_digits=12, verbose_name='Сумма')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takes', to=settings.AUTH_USER_MODEL, verbose_name='Заёмщик')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.Loan', verbose_name='Заём')),
            ],
        ),
    ]
