# Generated by Django 2.0.8 on 2018-09-26 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loan_transatcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrowers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Заемщики'),
        ),
    ]
