# Generated by Django 2.0.8 on 2018-09-27 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_loan_borrowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, help_text='в рублях', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takes', to=settings.AUTH_USER_MODEL, verbose_name='Заёмщик')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.Loan', verbose_name='Заём')),
            ],
        ),
        migrations.RemoveField(
            model_name='transatcion',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='transatcion',
            name='loan',
        ),
        migrations.DeleteModel(
            name='Transatcion',
        ),
    ]
